### ISSUE TITLE
[Android] "Font families missing in assets section" warning when running "build appbundle"

### ISSUE THREAD

**Issue by loolooii** [ez-connect/flutter-ionicons#17]
After running `flutter build appbundle`, I'm getting the following warning:

```
Expected to find fonts for (MaterialIcons, packages/Ionicons/Ionicons, packages/font_awesome_flutter/FontAwesomeBrands, packages/font_awesome_flutter/FontAwesomeSolid), but found (MaterialIcons, packages/font_awesome_flutter/FontAwesomeBrands, packages/font_awesome_flutter/FontAwesomeSolid). This usually means you are referring to font families in an IconData class but not including them in the assets section of your pubspec.yaml, are missing the package that would include them, or are missing "uses-material-design: true".
```

It doesn't break the build, but nevertheless pretty important I guess. 
There is a [StackOverflow question](https://stackoverflow.com/questions/74714969/ionicons-package-in-flutter-showing-this-warning-during-build-expected-to-find) about it as well.

I'm using version `0.2.1`

**Comment by vnhdx** [comment]
I can't reproduce the issue from my side. Can you try to build the app bundle in the `/example`, or upgrade to `v0.2.2`?

```bash
flutter build appbundle --no-tree-shake-icons
```

**Comment by loolooii** [comment]
@thanh-vinh Upgrading to `0.2.2` solved the issue for me. Thanks!

**Comment by nomoruyi** [comment]
Upgrading WHAT to 0.2.2??

**Comment by vnhdx** [comment]
@nomoruyi Update `ionicons` package in the `pubspec.yaml`

```yaml
# pubspec.yaml
dependencies:
  # v0.2.2
  ionicons: 0.2.2
  # Or v0.2.3
  ionicons:
    git:
      url: git@github.com:ez-connect/flutter-ionicons.git
      ref: v0.2.3
```
